version: '3.7'
services:
  soundshare:
    build:
      context: ../soundshare
      dockerfile: Dockerfile
    image: soundshare:latest
    volumes:
      - soundshare:/tmp/soundshare

  avahi:
    build:
      context: ../avahi
      dockerfile: Dockerfile
    image: avahi:latest
    ports:
      - 5353:5353/udp
  
  snapserver:
    depends_on:
      - avahi
      - soundshare
    build:
      context: ../snapserver
      dockerfile: Dockerfile
    image: snapserver:latest
    volumes:
      - soundshare:/tmp/soundshare
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780

  homeassistant:
    image: homeassistant/home-assistant:stable
    volumes:
      - /home/ray/Programs/homeassistant:/config
    ports:
      - 8123:8123

  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - /home/ray/Programs/mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
  
  spotifyd:
    depends_on:
      - snapserver
    build:
      context: ../spotifyd
      dockerfile: Dockerfile
    image: spotifyd:alex
    secrets: 
      - spotify_pwd_alex
    volumes:
      - soundshare:/tmp/soundshare

  deconz:
    image: marthoc/deconz:latest
    devices: 
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443
      - DECONZ_DEVICE=/dev/ttyACM0
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
      - /etc/localtime:/etc/localtime:ro

secrets:
  spotify_pwd_alex:
    file: spotify_pwd_alex.txt
  deconz_pwd:
    file: deconz_vnc_pwd.txt

volumes:
  soundshare:
